version: "3.7"
services:
  postgres:
    container_name: ${PROJECT_NAME}_postgres
    image: ${POSTGRES_IMAGE}
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default
    restart: always
volumes:
  postgres: