version: "3.7"

services:
###> doctrine/doctrine-bundle ###
  postgres:
    container_name: ${PROJECT_NAME}_postgres
    image: postgres:${POSTGRES_VERSION}-alpine3.16
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - default
    restart: always
###< doctrine/doctrine-bundle ###

  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: symfony_php
      args:
        PHP_VERSION: ${PHP_VERSION}
        CADDY_VERSION: ${CADDY_VERSION}
        APCU_VERSION: ${APCU_VERSION}
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        SYMFONY_SKELETON: ${SYMFONY_SKELETON:-symfony/skeleton}
        SYMFONY_STABILITY: ${SYMFONY_STABILITY:-stable}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
    depends_on:
      - postgres
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
      DATABASE_URL: ${POSTGRES_URL}
      # Run "composer require symfony/mercure-bundle" to install and configure the Mercure integration
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://caddy/.well-known/mercure}
      MERCURE_PUBLIC_URL: https://${SERVER_NAME:-localhost}/.well-known/mercure
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeMe!}

  caddy:
    container_name: ${PROJECT_NAME}_caddy
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: symfony_caddy
      args:
        PHP_VERSION: ${PHP_VERSION}
        CADDY_VERSION: ${CADDY_VERSION}
        APCU_VERSION: ${APCU_VERSION}
        SYMFONY_VERSION: ${SYMFONY_VERSION:-}
        SYMFONY_SKELETON: ${SYMFONY_SKELETON:-symfony/skeleton}
        SYMFONY_STABILITY: ${SYMFONY_STABILITY:-stable}
    depends_on:
      - php
    environment:
      PHP_VERSION: ${PHP_VERSION}
      SERVER_NAME: ${SERVER_NAME:-localhost, caddy:80}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeMe!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeMe!}
    restart: unless-stopped
    volumes:
      - php_socket:/var/run/php
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "${HTTP_PORT}:80/tcp"
      - "${HTTPS_PORT}:443/tcp"
      - "${HTTPS_PORT}:443/udp"

# Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  postgres:
###< doctrine/doctrine-bundle ###
  php_socket:
  caddy_data:
  caddy_config:
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
